import { defineStore } from "pinia";

export const productos = defineStore("productos", () => {
  const productos = [
    {
      id: 1,
      nombre: "Coca-Cola",
      categoria: "Refresco",
      descripcion: "Refresco de cola con gas",
      volumen_ml: 330,
      precio_venta: 2.5,
      cantidad_alcohol: 0,
      imagen: "/cocacola.png",
    },
    {
      id: 2,
      nombre: "Agua Mineral",
      categoria: "Agua",
      descripcion: "Agua mineral natural sin gas",
      volumen_ml: 500,
      precio_venta: 1.8,
      cantidad_alcohol: 0,
      imagen: "/aguamineral.png",
    },
    {
      id: 3,
      nombre: "Cerveza Lager",
      categoria: "Cerveza",
      descripcion: "Cerveza rubia tipo lager",
      volumen_ml: 330,
      precio_venta: 3.0,
      cantidad_alcohol: 5,
      imagen: "/cervezalager.png",
    },
    {
      id: 4,
      nombre: "Vino Tinto",
      categoria: "Vino",
      descripcion: "Vino tinto joven de la casa",
      volumen_ml: 150,
      precio_venta: 3.5,
      cantidad_alcohol: 13,
      imagen: "./vinotinto.png",
    },
    {
      id: 5,
      nombre: "Vino Blanco",
      categoria: "Vino",
      descripcion: "Vino blanco seco",
      volumen_ml: 150,
      precio_venta: 3.5,
      cantidad_alcohol: 12,
      imagen: "/vinoblanco.png",
    },
    {
      id: 6,
      nombre: "Fanta Naranja",
      categoria: "Refresco",
      descripcion: "Refresco de naranja dulce y burbujeante",
      volumen_ml: 330,
      precio_venta: 2.0,
      cantidad_alcohol: 0,
      imagen: "/fantanaranja.png",
    },
    {
      id: 7,
      nombre: "Red Bull",
      categoria: "Bebida Energética",
      descripcion: "Bebida energética para mantenerte activo",
      volumen_ml: 250,
      precio_venta: 3.0,
      cantidad_alcohol: 0,
      imagen: "/redbull.png",
    },
    {
      id: 8,
      nombre: "Zumo de Naranja",
      categoria: "Zumo",
      descripcion: "Zumo de naranja natural",
      volumen_ml: 250,
      precio_venta: 3.0,
      cantidad_alcohol: 0,
      imagen: "/zumonaranja.png",
    },
    {
      id: 9,
      nombre: "Gin Tonic",
      categoria: "Cóctel",
      descripcion: "Ginebra con tónica y limón",
      volumen_ml: 300,
      precio_venta: 8.0,
      cantidad_alcohol: 10,
      imagen: "/bombayshaphire.png",
    },
    {
      id: 10,
      nombre: "Whisky",
      categoria: "Licor",
      descripcion: "Whisky servido solo o con hielo",
      volumen_ml: 50,
      precio_venta: 7.0,
      cantidad_alcohol: 40,
      imagen: "/jackdaniels.png",
    },
  ];

  return { productos };
});
